const articles_data = [
  {
    // id: 'article0001',
    id: 'tango-history',
    title: 'Tango history',
    content:
      'TANGO HISTORY TEXT CONTENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in elementum nunc, eget ultricies est. Nunc nisi tortor, sollicitudin et gravida ac, finibus eu est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur aliquam massa vitae consectetur feugiat. Quisque in augue aliquam, tristique felis vitae, vulputate lacus. Curabitur rutrum magna non pellentesque luctus. Curabitur eget luctus tortor. Vivamus vestibulum ornare posuere. Nullam sollicitudin tellus mauris, ornare finibus erat vehicula non. Morbi accumsan, augue sed eleifend feugiat, dui ipsum blandit mauris, non varius nunc nibh a augue. Integer venenatis nisl non neque elementum, sit amet varius magna pulvinar. Ut sit amet nibh suscipit, elementum elit iaculis, mollis odio. Quisque in rhoncus dui. Duis sit amet ipsum viverra, faucibus metus quis, sagittis nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id suscipit odio, nec auctor magna. Donec et ultricies tortor, non elementum sapien. Praesent sed felis urna. Proin enim lorem, ultrices ut lorem in, tincidunt hendrerit turpis. Proin maximus nibh non lacus luctus, in rhoncus dui venenatis. Morbi laoreet tincidunt dictum. In dignissim dolor ac ligula rutrum, vitae blandit ex fringilla. Ut nec vehicula lorem. Cras ornare tortor vulputate feugiat venenatis. Suspendisse vel ex vulputate, elementum odio eu, dignissim felis. Donec tellus tortor, varius quis venenatis elementum, porttitor a mi. Proin ultrices, arcu id efficitur pretium, nunc enim molestie arcu, quis ultricies nisi sapien ac tortor. Pellentesque pretium nisi ac nunc gravida, sit amet rutrum eros porta. Aliquam semper, felis at ultricies scelerisque, diam turpis cursus neque, a dictum lorem sem nec erat.',
  },
  {
    // id: 'article0002',
    id: 'orchestras',
    title: 'Orchestras',
    content:
      'ORCHESTRAS TEXT CONTENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in elementum nunc, eget ultricies est. Nunc nisi tortor, sollicitudin et gravida ac, finibus eu est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur aliquam massa vitae consectetur feugiat. Quisque in augue aliquam, tristique felis vitae, vulputate lacus. Curabitur rutrum magna non pellentesque luctus. Curabitur eget luctus tortor. Vivamus vestibulum ornare posuere. Nullam sollicitudin tellus mauris, ornare finibus erat vehicula non. Morbi accumsan, augue sed eleifend feugiat, dui ipsum blandit mauris, non varius nunc nibh a augue. Integer venenatis nisl non neque elementum, sit amet varius magna pulvinar. Ut sit amet nibh suscipit, elementum elit iaculis, mollis odio. Quisque in rhoncus dui. Duis sit amet ipsum viverra, faucibus metus quis, sagittis nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id suscipit odio, nec auctor magna. Donec et ultricies tortor, non elementum sapien. Praesent sed felis urna. Proin enim lorem, ultrices ut lorem in, tincidunt hendrerit turpis. Proin maximus nibh non lacus luctus, in rhoncus dui venenatis. Morbi laoreet tincidunt dictum. In dignissim dolor ac ligula rutrum, vitae blandit ex fringilla. Ut nec vehicula lorem. Cras ornare tortor vulputate feugiat venenatis. Suspendisse vel ex vulputate, elementum odio eu, dignissim felis. Donec tellus tortor, varius quis venenatis elementum, porttitor a mi. Proin ultrices, arcu id efficitur pretium, nunc enim molestie arcu, quis ultricies nisi sapien ac tortor. Pellentesque pretium nisi ac nunc gravida, sit amet rutrum eros porta. Aliquam semper, felis at ultricies scelerisque, diam turpis cursus neque, a dictum lorem sem nec erat.',
  },
  {
    // id: 'article0003',
    id: 'singers',
    title: 'Singers',
    content:
      'SINGERS TEXT CONTENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in elementum nunc, eget ultricies est. Nunc nisi tortor, sollicitudin et gravida ac, finibus eu est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur aliquam massa vitae consectetur feugiat. Quisque in augue aliquam, tristique felis vitae, vulputate lacus. Curabitur rutrum magna non pellentesque luctus. Curabitur eget luctus tortor. Vivamus vestibulum ornare posuere. Nullam sollicitudin tellus mauris, ornare finibus erat vehicula non. Morbi accumsan, augue sed eleifend feugiat, dui ipsum blandit mauris, non varius nunc nibh a augue. Integer venenatis nisl non neque elementum, sit amet varius magna pulvinar. Ut sit amet nibh suscipit, elementum elit iaculis, mollis odio. Quisque in rhoncus dui. Duis sit amet ipsum viverra, faucibus metus quis, sagittis nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id suscipit odio, nec auctor magna. Donec et ultricies tortor, non elementum sapien. Praesent sed felis urna. Proin enim lorem, ultrices ut lorem in, tincidunt hendrerit turpis. Proin maximus nibh non lacus luctus, in rhoncus dui venenatis. Morbi laoreet tincidunt dictum. In dignissim dolor ac ligula rutrum, vitae blandit ex fringilla. Ut nec vehicula lorem. Cras ornare tortor vulputate feugiat venenatis. Suspendisse vel ex vulputate, elementum odio eu, dignissim felis. Donec tellus tortor, varius quis venenatis elementum, porttitor a mi. Proin ultrices, arcu id efficitur pretium, nunc enim molestie arcu, quis ultricies nisi sapien ac tortor. Pellentesque pretium nisi ac nunc gravida, sit amet rutrum eros porta. Aliquam semper, felis at ultricies scelerisque, diam turpis cursus neque, a dictum lorem sem nec erat.',
  },
];

export default articles_data;
